### ISSUE TITLE
[QUESTION] Moving from ESPHOME to Homekit Branch

### ISSUE THREAD

**Issue by edrikk** [ratgdo/homekit-ratgdo#131]
Hi,

I'm lurking here (great, great work recently) to keep up to date on how things are progressing.
In the meantime, I'm using ESPHome firmware with Homebridge to expose to Homekit.

If I want to actually try out the HK firmware, given that ESPHome version allows for OTA/online uploading of the flash file, is it sufficient to simply upload the HK Firmware or does one need to still connect via USB and webflash for first flash?

I guess asked another way, does the HK firmware provide an AP that one can connect to if flashed without USB so that you can change the IP Address of device and Pair to homekit, or is that a part of the initial USB web flash process?

If USB is needed, it would be really awesome if the UI could be updated to allow for this capability as although not impossible to bring a laptop to the device, it would make life a lot simpler when testing different flavours etc.

Thanks so much!

**Comment by jgstroud** [comment]
Never tried it but you should be able to upload the HK bin to the ESPHome OTA and it will probably come back up with the same wifi settings.  But I would probably recommend using the usb update and do a full flash erase and reprogram since you are switching from ESPHome.

HomeKit firmware does not support AP mode.  You need to configure your WiFi using the USB cable.  Also, we only support DHCP mode and do no support manually setting the IP settings.  Feel free to open a feature request if you want.
