### ISSUE TITLE
HomeKit garage door not working after 1.5 update

### ISSUE THREAD

**Issue by bob3k3** [ratgdo/homekit-ratgdo#198]
After 1.5 update, HomeKit would not connect to door and icon will not control either door or light. I deleted the HomeKit Garage Door control from the Home app and then tried to associate the garage door again with it. I got a message that the garage door was associated with another home. And then tried to reinstall the software and I also get a message."WARNING: Flash CRC check failed. You must flash new firmware by USB cable to recover, please consult documentation. RATGDO device may not restart if you reboot now. Reboot anyway?"  

Not sure if this issue is something that I did wrong. Probably.

Issue was resolved by flashing firmware by USB cable to the RATGDO.

**Comment by jgstroud** [comment]
Probably less that you did something wrong and more that the firmware prior to 1.5 had a pretty fatal bug.  Since you have the CRC error, you probably need to reflash from USB.  As @dkerr64 put it:
I have found that the most reliable way to do this is 1) erase from Apple Home, 2) reset/re-pair button on ratgdo, 3) kill Apple Home and restart it and 4) scan the QR code.

**Comment by bob3k3** [comment]
Thanks, that’s exactly what I did and everything’s working fine. Love the Ratgdo! Best, BobOn Jun 5, 2024, at 7:02 PM, jgstroud ***@***.***> wrote:﻿
Probably less that you did something wrong and more that the firmware prior to 1.5 had a pretty fatal bug.  Since you have the CRC error, you probably need to reflash from USB.  As @dkerr64 put it:
I have found that the most reliable way to do this is 1) erase from Apple Home, 2) reset/re-pair button on ratgdo, 3) kill Apple Home and restart it and 4) scan the QR code.
