### ISSUE TITLE
Allow setting different username

### ISSUE THREAD

**Issue by donavanbecker** [ratgdo/homekit-ratgdo#225]
would be nice if the username could be changed from admin to something else.

**Comment by dkerr64** [comment]
Request noted.  Yes username could be changed, just a small matter of programming it.  Will consider for a future release.

**Comment by donavanbecker** [comment]
With that would multi user support be useful?

**Comment by dkerr64** [comment]
> With that would multi user support be useful?

I think that is a stretch.  Much more complex to implement, and what's the point?  I don't want to encourage use of the web interface... it should be for admin purposes only.  Apple Home or other HomeKit apps is how most should interact with the door, not the web page.

I can think of a (quite niche case) where changing from "admin" to something else may be useful, but I'm not seeing it for multiuser.

David

**Comment by donavanbecker** [comment]
Totally understand, I don't need it but figured I would propose it.

**Comment by dkerr64** [comment]
Will implement in next release whenever we do that... is in PR #227

**Comment by donavanbecker** [comment]
Working awesome @dkerr64!!

Anyway to change the login pop up so that it supports autofill on mobile?

![image](https://github.com/user-attachments/assets/288716d1-ce37-4199-9160-b741defa6b8e)

**Comment by dkerr64** [comment]
We're using basic browser-based digest authentication.  The popup is generated by the browser so, AFAIK, I cannot influence how that popup appears or whether the mobile (or desktop) browser will offer to autofill the fields.

The alternative would be to implement our own login dialog... that requires we implement our own and not rely on browser-based digest authentication.  This, in-fact, is best practice which is why you rarely see browser popups for userid/password anymore on web sites (it's considered insecure).  But a lot of work I think and I'm not sure it is worth the effort especially given we cannot implement SSL (https).

**Comment by dkerr64** [comment]
included in v1.7.1
