### ISSUE TITLE
Rename Network Name / Fixed IP Address

### ISSUE THREAD

**Issue by djducat** [ratgdo/homekit-ratgdo#231]
Having the ability to rename the unit from the factory name to a user defined name would help to identify it on the network.  Especially when you have multiple garage doors.  Default name like esp-0b011f is not ideal.  Also, being able to specify an IP address instead of using DHCP would be a nice enhancement.

**Comment by dkerr64** [comment]
Static IP is doable, just not something we prioritized.  I can certainly look at it again.  I thought that I had the user defined name done... you can provide a custom name on the web page.  But you are right that it is not affecting what the network sees as hostname, which is odd because I'm pretty sure that was working in the past.  I'll take a look at it.

Thanks for opening this, I'll mark it as enhancement and keep it open for now.

**Comment by dkerr64** [comment]
Static IP address will be supported in next release.  I just added it to PR #227

IP host name was not being set, so I fixed that in the same commit.

Thank you for prompting me to loot at this.

**Comment by djducat** [comment]
wow!  you guys don't waste any time, do you?  :)

**Comment by jgstroud** [comment]
Thanks David.  I coded up the hostname fix at one point but I was having some issue with it and never pushed it.  I'm glad you took care of that.  Thanks

**Comment by dkerr64** [comment]
included in v1.7.1
