### ISSUE TITLE
allow customization of syslog port

### ISSUE THREAD

**Issue by SShah7433** [ratgdo/homekit-ratgdo#245]
Allow for syslog to be sent to ports other than 514. Many syslog listeners use ports to segment data or listen on non-privileged ports.

**Comment by jgstroud** [comment]
How important is that feature to you?  The feature is trivial to implement, but IMHO, seems excessive for this device and use case.  For segmenting data, syslog has different logging facilities, which we use LOCAL0, and it also filters based on hostname.  out of the box rsyslog creates separate logs for every remote host.  

Every setting we add has the downside of chewing up previous bytes of RAM, so I want to understand how important it is.  Also, if we do implement, it must remain UDP.  While technically possible, we definitely will not implement TCP because it has major memory usage implications.

**Comment by SShah7433** [comment]
It's nice to have, but it's a low priority. I can work around it fairly easily, so in the spirit of preserving memory for more requested features, let's backlog this.

**Comment by jgstroud** [comment]
Thanks for the update.  It's a mostly trivial feature, so we may still add this but we have a few higher priority tasks at the moment.

**Comment by dkerr64** [comment]
Added in PR #247 so will be in next release whenever we do that.

**Comment by phybersplice** [comment]
Absolutely no rush. 
Thank you.  Very much appreciated whenever it can be implemented.

**Comment by dkerr64** [comment]
Implemented in 1.8.2
